# Generated by Django 3.1 on 2020-09-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200918_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
