# Generated by Django 3.1 on 2020-09-21 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200918_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closebid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='closebid',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='closebid',
            name='winner',
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='Active', max_length=6),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bid_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listing_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='CloseBid',
        ),
    ]
