# Generated by Django 3.1 on 2020-09-21 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200921_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listing',
        ),
    ]
